const items = [
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
    
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',
  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
    store: '',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف مناسب مدرسه و مهد کودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
    personal: '',
  },
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
    
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',
    
  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف کودک مناسب مدرسه و مهدکودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
    personal: '',
  },
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',
  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف کودک مناسب مدرسه و مهدکودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
  },
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',
    personal: '',
  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
    personal: '',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف کودک مناسب مدرسه و مهدکودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
    personal: '',
  },
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',

  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف کودک مناسب مدرسه و مهدکودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
    personal: '',
  },
  {
    img: '../../../src/img/img/gYJzhCWO.jpg',
    title: 'مبلمان نگین غرب',
    conditon: 'نو',
    price: '8,000,000',
    location: 'مبلمان نگین غرب',
    personal: '',
  },
  {
    img: '../../../src/img/img/wY91NyQu.jpg',
    title: 'یخچال ساید بای ساید دوو مدل D2S-0033SS',
    conditon: 'نو',
    price: '24,000,000',
    location: 'ایران (دوو اسنوا)',
    personal: '',
  },
  {
    img: '../../../src/img/img/wY9FeDH2.jpg',
    title: 'یخچال ساید بای ساید اسنوا 2322',
    conditon: 'نو',
    price: '23,500,000',
    location: 'ایران (دوو اسنوا)',
  },
  {
    img: '../../../src/img/img/wYsDPWou.jpg',
    title: 'روکش صندلی با ضمانت',
    conditon: 'کار کرده',
    price: 'توافقی',
    location: 'لحظاتی پیش در مشیریه',
  },
  {
    img: '../../../src/img/img/wYvHo71k.jpg',
    title: 'میز نهار خوری 4 نفره',
    conditon: 'کار کرده',
    price: '2,200,000',
    location: 'لحظاتی پیش در دارآباد',
  },
  {
    img: '../../../src/img/img/wYvHo7qO.jpg',
    title: 'کیف کودک مناسب مدرسه و مهدکودک',
    conditon: 'در حد نو',
    price: '80,000',
    location: 'لحظاتی پیش در شهرک ولیعصر',
    personal: '',
  },
  
];
export default items;
